blank_issues_enabled: false
contact_links:
  - name: Grid Cutting Patterns on the Steam Workshop
    url: https://steamcommunity.com/sharedfiles/filedetails/?id=3739849811
    about: Subscribe, rate, or leave a comment / quick question here.
  - name: Growth & Harvest Heatmap on the Steam Workshop
    url: https://steamcommunity.com/sharedfiles/filedetails/?id=3751029877
    about: Subscribe, rate, or leave a comment / quick question here.
  - name: Pattern Planting on the Steam Workshop
    url: https://steamcommunity.com/sharedfiles/filedetails/?id=3746114393
    about: Subscribe, rate, or leave a comment / quick question here.
  - name: Support on Ko-fi
    url: https://ko-fi.com/jamejacko
    about: Buy me a coffee (never required).
